compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@4.6.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"
      - "@openzeppelin2=OpenZeppelin/openzeppelin-contracts@4.6.0"

networks:
  default: development

wallets:
  owner: ${OWNER_PRIVATE_KEY}
  attacker: ${ATTACKER_PRIVATE_KEY}
dotenv: .env